service: townhub-services-towns

provider:
  name: aws
  runtime: ${file(../shared/provider.yml):runtime}
  region: ${file(../shared/provider.yml):region}
  profile: ${file(../shared/provider.yml):profile}
  stage: ${file(../shared/provider.yml):stage}
  apiGateway: ${file(../shared/api-gateway.yml)}
  environment:
    TOWNS_DATABASE_NAME: ${self:custom.towns.tables.towns.name}
  iamRoleStatements:
    - ${self:custom.towns.tableIamRoles.townsTable}

package:
  individually: true

custom:
  cors: ${file(../shared/cors.yml)}
  towns: ${file(../shared/modules/towns.yml)}
  rollup:
    config: ../../build/rollup.config.deploy.js
    installCommand: yarn add

plugins:
  - serverless-rollup-plugin

functions:
  getByHid:
    handler: src/get-by-hid.main
    events:
      - http:
          path: towns/hid/{townHid}
          method: get
          cors: ${self:custom.cors}
