# Deploy different apps to a dev environment
name: Deploy Apps to Development Environment

on:
  push:
    branches:
      - chore-deploy-dev
    # paths:
      # - 'apps/**'
      # - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      # Cache Yarn packages to reduce install time
      - uses: c-hive/gha-yarn-cache@v1
      # Run install and test
      - run: yarn install
      - run: yarn test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Apps
        run: yarn run build:apps
      - name: Upload to S3
        run: aws --version

