# Deploy different apps to a dev environment
name: Deploy Apps to Development Environment

on:
  push:
    branches:
      - master
    paths:
      - 'apps/**'
      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    env:
      REACT_APP_TOWNHUB_API_ENDPOINT: ${{ secrets.TOWNHUB_API_ENDPOINT }}
      REACT_APP_MAP_BOX_API_KEY: ${{ secrets.MAP_BOX_API_KEY }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      # Cache Yarn packages to reduce install time
      - uses: c-hive/gha-yarn-cache@v1
      # Run install and test
      - run: yarn install
      - run: yarn run build:libs
      - run: yarn test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Apps
        # CI is set to false here to supress warnings as errors as React is
        # complaining of unused variables even though they are all imported
        # types from typescript libraries
        # https://github.com/typescript-eslint/typescript-eslint/issues/2714
        run: CI=false yarn run build:apps
      - name: Upload to S3
        run: aws s3 sync apps/web/build ${{ secrets.TOWNHUB_APP_BUCKET_S3_URL }} --acl public-read
